version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  go: circleci/go@1.7.3

jobs:
  test-app:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./ ...)

  build-app-karsajobs:
    docker:
      - image: cimg/base:2020.01
    environment:
      IMAGE_NAME: ghcr.io/hario86/karsajobs
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to GitHub Container Registry
          command: |
            echo "$CR_PAT" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  ci:
    jobs:
      - docker/hadolint:
          dockerfiles: './Dockerfile'
      - test-app
      - build-app-karsajobs:
          requires:
            - docker/hadolint
            - test-app
