# Versi API yang di definisikan
apiVersion: v1
# Jenis Objek Kubernetes (Secret)
kind: Secret
# Metadata untuk Deployment
metadata:
  # Nama Secret
  name: mongo-credentials
# Tipe data yang akan di simpan dalam Secret
type: Opaque
# Data yang akan disimpan dalam Secret
data:
# Data dengan key MONGO_ROOT_USERNAME dalam bentuk encode
  MONGO_ROOT_USERNAME: YWRtaW4=
# Data dengan key MONGO_ROOT_PASSWORD dalam bentuk encode
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
